application: mic
version: 1
runtime: python
api_version: 1
default_expiration: "0d 0h"

handlers:
- url: /js/
  static_dir: js2/
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /.*
  script: mic.py
